# These are supported funding model platforms

github: palpalani
# patreon: # Replace with up to 4 Patreon usernames
# open_collective: # Replace with one Open Collective username
# ko_fi: # Replace with one Ko-fi username
# tidelift: # Replace with one Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with one Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with one Liberapay username
# issuehunt: # Replace with one IssueHunt username
# otechie: # Replace with one Otechie username
# lfx_crowdfunding: # Replace with one LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with one Polar username
# buy_me_a_coffee: # Replace with one Buy Me a Coffee username
# thanks_dev: # Replace with one thanks.dev username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

